language: r
warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
  - jimhester/covr
  - jimhester/lintr

after_success:
  - Rscript -e 'library(covr);codecov()'
  - Rscript -e 'lintr::lint_package()'
